CC = gcc -Wall -Wextra -Werror

NAME = ft_check_filemap.c \
		ft_check_format.c \
		ft_create_game.c \
		ft_so_long.c \
		ft_valid_path.c \

HEADER = ft_so_long.h \
		color.h

LIBX = -L mlx_linux -lmlx_Linux

LIBXFLAGS = -lmlx -lXext -lX11 -lmlx_Linux

$(MAKE) :	$(MAKE) --no-print-directory -C libft
			$(MAKE) --no-print-directory -C libft
			$(CC) $(FLAGS) 